# Generated by Django 4.0.3 on 2022-04-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(max_length=500, verbose_name='Business_Name')),
                ('OperatingYears', models.IntegerField(verbose_name='OperatingYears')),
                ('BusinessType', models.CharField(choices=[('Micro', 'MicroEnterprise'), ('Small', 'SmallEnterprise'), ('Medium', 'MediumEnterprise'), ('Macro', 'MacroEnterprise')], max_length=500, verbose_name='Business_Type')),
                ('MonthlyIncome', models.IntegerField(verbose_name='Monthly_Income')),
                ('BusCounty', models.CharField(max_length=500, verbose_name='Bus_County')),
                ('BusSubCounty', models.CharField(max_length=500, verbose_name='Bus_SubCounty')),
                ('BusDistrict', models.CharField(max_length=500, verbose_name='Bus_District')),
                ('BusLocation', models.CharField(max_length=500, verbose_name='Bus_Location')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GFirstName', models.CharField(max_length=500, verbose_name='Guarantor_FName')),
                ('GLastName', models.CharField(max_length=500, verbose_name='Guarantor_LName')),
                ('GTelephone', models.IntegerField(verbose_name='Guarantor_Telephone')),
                ('GResidence', models.CharField(max_length=500, verbose_name='Guarantor_Residence')),
                ('Relationship', models.CharField(max_length=100, verbose_name='Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=500, verbose_name='FirstName')),
                ('LastName', models.CharField(max_length=500, verbose_name='LastName')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('Id_Passport', models.IntegerField(verbose_name='Id/Passport')),
                ('Phone', models.IntegerField(verbose_name='Phone')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('Dob', models.DateField(verbose_name='Dob')),
                ('Picture', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='')),
                ('County', models.CharField(max_length=500, verbose_name='County')),
                ('SubCounty', models.CharField(max_length=500, verbose_name='SubCounty')),
                ('District', models.CharField(max_length=500, verbose_name='District')),
                ('Location', models.CharField(max_length=500, verbose_name='Location')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanApp.business', verbose_name='business')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanApp.guarantor', verbose_name='guarantor')),
            ],
        ),
    ]
