# Generated by Django 4.0.3 on 2022-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0002_alter_business_businesstype_alter_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoanNumber', models.IntegerField(verbose_name='Loan Number')),
                ('Amount', models.IntegerField(verbose_name='Loan Amount')),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, verbose_name='Loan Status')),
            ],
        ),
    ]
