# Generated by Django 4.0.3 on 2022-04-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LoanApp.customer'),
        ),
    ]
