# Generated by Django 4.0.3 on 2022-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0004_loan_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='LoanAmount',
            field=models.IntegerField(default=10000, verbose_name='Loan_Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending', max_length=100, verbose_name='Loan Status'),
        ),
    ]
