# Generated by Django 4.0.3 on 2022-04-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_business_loanamount_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Picture',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='UserImages'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='LoanNumber',
            field=models.IntegerField(unique=True, verbose_name='Loan Number'),
        ),
    ]
