# Generated by Django 4.0.3 on 2022-04-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0007_alter_loan_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='guarantor',
        ),
        migrations.AddField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Picture',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='UserImages/'),
        ),
    ]
