# Generated by Django 4.0.3 on 2022-04-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0008_remove_customer_business_remove_customer_guarantor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.customer', verbose_name='customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanApp.customer', verbose_name='customer'),
        ),
    ]
