# Generated by Django 4.0.3 on 2022-04-13 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoanApp', '0009_alter_business_customer_alter_guarantor_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Field Officer', 'Field Officer'), ('Supervisor', 'Supervisor'), ('Administrator', 'Administrator')], max_length=100, verbose_name='Category')),
                ('Photo', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='ProfilePictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
