# Generated by Django 4.0.3 on 2022-04-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0011_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(verbose_name='Payment Amount')),
                ('Type', models.CharField(choices=[('Processing Fee', 'Processing Fee'), ('First Instalment', 'First Instalment'), ('Second Instalment', 'Second Instalment'), ('Penalty', 'Penalty')], max_length=200, verbose_name='Payment type')),
                ('DatePaid', models.DateTimeField(auto_now_add=True, verbose_name='Date Paid')),
                ('Status', models.CharField(choices=[('Late', 'Late'), ('Timely', 'Timely')], max_length=255, verbose_name='Payment Status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.customer', verbose_name='customer')),
                ('loan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loan', verbose_name='loan')),
            ],
        ),
    ]
