# Generated by Django 4.0.3 on 2022-04-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='officer',
            field=models.CharField(max_length=255, null=True, verbose_name='Field_Officer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='supervisor',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor'),
        ),
    ]
