# Generated by Django 4.0.3 on 2022-04-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0013_loan_officer_loan_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Paid', 'Paid'), ('Defaulted', 'Defaulted')], default='Pending', max_length=100, verbose_name='Loan Status'),
        ),
    ]
