# Generated by Django 4.0.3 on 2022-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0014_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Remark',
            field=models.CharField(default='Approved', max_length=255, verbose_name='Remark'),
        ),
    ]
