# Generated by Django 4.0.3 on 2022-04-18 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0015_loan_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7000)], verbose_name='Loan Amount'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Paid', 'Paid'), ('Defaulted', 'Defaulted'), ('Disbursed', 'Disbursed')], default='Pending', max_length=100, verbose_name='Loan Status'),
        ),
    ]
