# Generated by Django 4.0.3 on 2022-04-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0016_alter_loan_amount_alter_loan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
